version: "3.7"

services:
  blockchain-modelling-tool:
    image: blockchain-modelling-tool:0.1.0
    build:
      context: . # relative to docker-compose.yml
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    restart: unless-stopped
